#!/bin/bash

if [ "$#" -lt 2 ]; then
        printf "\n\n###### Usage\n\n"
        printf "$0 <PATH to params.txt file> <PATH to cuffquant DIR(s)> <Comparison Group(s)>\n\n"
        exit
fi

if [ ! -d cuffdiff ]
then
        mkdir cuffdiff
fi

params=`cat $1 | grep '^cuffdiff' | cut -f2`
shift

cuffquant=$1
shift

COMPARISON_LIST=($@)

for comparison in ${COMPARISON_LIST[@]}
do
	base_name=`basename $comparison`
	mkdir cuffdiff/$base_name
	treatment=`echo $base_name | cut -d'.' -f1`
	control=`echo $base_name | cut -d'.' -f3`


echo "#!/bin/bash" > cuffdiff/${treatment}".vs."${control}/run.bash
echo "prog_dir=\`dirname \$0\`" >> cuffdiff/${treatment}".vs."${control}/run.bash
echo "cd \$prog_dir" >> cuffdiff/${treatment}".vs."${control}/run.bash
echo "cd ../" >> cuffdiff/${treatment}".vs."${control}/run.bash
printf "~/utilities/cufflinks/cuffdiff $params -o ${treatment}.vs.${control} -L ${treatment},${control} " >> cuffdiff/${treatment}".vs."${control}/run.bash
cat $comparison/1_group_info.tsv | awk '$2~/^'${treatment}'$/{printf "../'${cuffquant}'/"$1"/abundances.cxb,"}' | sed '1,$s/,$/ /g' >> cuffdiff/${treatment}".vs."${control}/run.bash
cat $comparison/1_group_info.tsv | awk '$2~/^'${control}'$/{printf "../'${cuffquant}'/"$1"/abundances.cxb,"}' | sed '1,$s/,$/ /g' >> cuffdiff/${treatment}".vs."${control}/run.bash

echo "cd "${treatment}.vs.${control} >> cuffdiff/${treatment}".vs."${control}/run.bash

echo "~/utilities/yixiao_scripts/rnaseq_cuffdiff_post gene_exp.diff " >> cuffdiff/${treatment}".vs."${control}/run.bash

done
